### ISSUE TITLE
Aria2 在路由器UI界面无法开启运行，也无法开机启动

### ISSUE THREAD

**Issue by LarryLi-cn** [trombonist852/multi-device-openwrt#1]
Aria2 在路由器UI界面无法开启运行，也无法开机启动
硬件：R2S

**Comment by trombonist852** [comment]
> Aria2 在路由器UI界面无法开启运行，也无法开机启动
> 硬件：R2S

这个是上游代码的原因 还没有修复 包括docker也是有冲突 等待修复吧 目前aria2可以尝试在ui界面配置好后到系统-启动项里尝试手动启动。

**Comment by LarryLi-cn** [comment]
多谢解答，手动是可以启动的，有没有办法可以开机自运行？我自己在rc.local和init.d里边都添加了开机脚本结果还是失败，还有别的办法吗？

**Comment by trombonist852** [comment]
> 多谢解答，手动是可以启动的，有没有办法可以开机自运行？我自己在rc.local和init.d里边都添加了开机脚本结果还是失败，还有别的办法吗？

按理说照这样设置好之后再重启他就是运行的状态了啊  不过我现在用的是docker的aria2 pro 比这个好用多了 有兴趣你可以试试
https://p3terx.com/archives/docker-aria2-pro.html

**Comment by LarryLi-cn** [comment]
多谢解答
我的开机启动配置如下：
1、在rc.local里添加了：
sleep 60s
sh /etc/init.d/aria2 start
仍无法开机启动
2、在init.d里新建了只有两天条命令行：
 sleep 60s
sh /etc/init.d/aria2 start
的脚本并加入了开机启动项
仍然失败。
3. 改天学习一下docker,  你说这个固件docker也有冲突？ 那可以装这个aria2 pro吗？

**Comment by trombonist852** [comment]
> 多谢解答
> 我的开机启动配置如下：
> 1、在rc.local里添加了：
> sleep 60s
> sh /etc/init.d/aria2 start
> 仍无法开机启动
> 2、在init.d里新建了只有两天条命令行：
> sleep 60s
> sh /etc/init.d/aria2 start
> 的脚本并加入了开机启动项
> 仍然失败。
> 3. 改天学习一下docker, 你说这个固件docker也有冲突？ 那可以装这个aria2 pro吗？

可以装，手动配置一下/etc/config/dockerd里面的配置文件路径就可以了

**Comment by LarryLi-cn** [comment]
> > 多谢解答
> > 我的开机启动配置如下：
> > 1、在rc.local里添加了：
> > sleep 60s
> > sh /etc/init.d/aria2 start
> > 仍无法开机启动
> > 2、在init.d里新建了只有两天条命令行：
> > sleep 60s
> > sh /etc/init.d/aria2 start
> > 的脚本并加入了开机启动项
> > 仍然失败。
> > 3. 改天学习一下docker, 你说这个固件docker也有冲突？ 那可以装这个aria2 pro吗？
> 
> 可以装，手动配置一下/etc/config/dockerd里面的配置文件路径就可以了

配置文件路径指向哪里？

**Comment by trombonist852** [comment]
没要求的话保持默认就好

**Comment by LarryLi-cn** [comment]
关于aria2  网上找了一个监控进程的脚本，配置成每隔一段时间检查一下aria2c进程还在不在，不在就拉起。
另外，我发现在路由器webui端aria2配置界面修改的参数需要重启aria2才会生效；
在AriaNg界面修改的配置根本不会起作用，重启aria2还是原来的配置

**Comment by trombonist852** [comment]
> 关于aria2 网上找了一个监控进程的脚本，配置成每隔一段时间检查一下aria2c进程还在不在，不在就拉起。
> 另外，我发现在路由器webui端aria2配置界面修改的参数需要重启aria2才会生效；
> 在AriaNg界面修改的配置根本不会起作用，重启aria2还是原来的配置
对的  上游代码的bug，直接到/etc/config下手动修改aria2的配置文件吧 这样最靠谱

**Comment by LarryLi-cn** [comment]
> 没要求的话保持默认就好

dockerman ui上的配置都没用了吗？只能自己手动改/etc/config/dockerd？

**Comment by LarryLi-cn** [comment]
> > 关于aria2 网上找了一个监控进程的脚本，配置成每隔一段时间检查一下aria2c进程还在不在，不在就拉起。
> > 另外，我发现在路由器webui端aria2配置界面修改的参数需要重启aria2才会生效；
> > 在AriaNg界面修改的配置根本不会起作用，重启aria2还是原来的配置
> > 对的  上游代码的bug，直接到/etc/config下手动修改aria2的配置文件吧 这样最靠谱

还有一个问题：添加中文任务，生成的文件夹文件名乱码怎么解决？

**Comment by trombonist852** [comment]
> > 没要求的话保持默认就好
> 
> dockerman ui上的配置都没用了吗？只能自己手动改/etc/config/dockerd？

对的  目前是这样  看看上游啥时候能修复吧  不是说快出正式版了么 估计正式版应该能修复了

**Comment by LarryLi-cn** [comment]
> > > 关于aria2 网上找了一个监控进程的脚本，配置成每隔一段时间检查一下aria2c进程还在不在，不在就拉起。
> > > 另外，我发现在路由器webui端aria2配置界面修改的参数需要重启aria2才会生效；
> > > 在AriaNg界面修改的配置根本不会起作用，重启aria2还是原来的配置
> > > 对的  上游代码的bug，直接到/etc/config下手动修改aria2的配置文件吧 这样最靠谱
> 
> 还有一个问题：添加中文任务，生成的文件夹文件名乱码怎么解决？

已解决，挂载远程nas时添加参数：
mount -t cifs //192.168.50.253/ST_Media -o username=***,password=***,vers=1.0,iocharset=utf8,sec=ntlm /mnt/nas/ST_Media

**Comment by LarryLi-cn** [comment]
> > > 没要求的话保持默认就好
> > 
> > 
> > dockerman ui上的配置都没用了吗？只能自己手动改/etc/config/dockerd？
> 
> 对的 目前是这样 看看上游啥时候能修复吧 不是说快出正式版了么 估计正式版应该能修复了

多谢~  等等再折腾吧~
