### ISSUE TITLE
小白请教：SSH连接在线修改config后怎么将配置文件下载下来以备下次编译？

### ISSUE THREAD

**Issue by LarryLi-cn** [trombonist852/multi-device-openwrt#2]
如题

**Comment by trombonist852** [comment]
> 如题

系统-文件传输-下载到本地下输入/etc，然后点下载到本地

**Comment by LarryLi-cn** [comment]
系统-文件传输-下载到本地  这是在哪里？我是编译的时候使能了ssh  然后make menuconfig，配置完了想把.config保存下来。

**Comment by trombonist852** [comment]
> 系统-文件传输-下载到本地 这是在哪里？我是编译的时候使能了ssh 然后make menuconfig，配置完了想把.config保存下来。

本地配置好后把.config传上去就可以了

**Comment by LarryLi-cn** [comment]
> > 系统-文件传输-下载到本地 这是在哪里？我是编译的时候使能了ssh 然后make menuconfig，配置完了想把.config保存下来。
> 
> 本地配置好后把.config传上去就可以了
多谢解答
我的意思是将在线云编译的.config保存下来，不是上传本地的.config，
我修改了yml文件，将.config复制到了target目录下跟系统镜像一起打包了~
