### ISSUE TITLE
求教docker无法拉取镜像

### ISSUE THREAD

**Issue by ericedwars** [trombonist852/multi-device-openwrt#4]
Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on [::1]:53: server misbehaving

求教大佬该如何设置？

**Comment by trombonist852** [comment]
> Error response from daemon: Get "https://registry-1.docker.io/v2/": dial tcp: lookup registry-1.docker.io on [::1]:53: server misbehaving
> 
> 求教大佬该如何设置？

换国内源或者挂代理试试
