### ISSUE TITLE
最新的几个x86版本都有相同bug

### ISSUE THREAD

**Issue by gexqin** [trombonist852/multi-device-openwrt#6]
安装好之后无法修改接口 ，点到--网络--接口 
报错如下

Network ifname configuration migration
为了使 LuCI 正常工作，现有的网络配置需要更改。
Upon pressing "Continue", ifname options will get renamed and the network will be restarted to apply the updated configuration.

**Comment by trombonist852** [comment]
> 安装好之后无法修改接口 ，点到--网络--接口
> 报错如下
> 
> Network ifname configuration migration
> 为了使 LuCI 正常工作，现有的网络配置需要更改。
> Upon pressing "Continue", ifname options will get renamed and the network will be restarted to apply the updated configuration.

你先去下29号的版本，29号的没问题，我去修复下等晚上下新版本试试看

**Comment by trombonist852** [comment]
> 安装好之后无法修改接口 ，点到--网络--接口
> 报错如下
> 
> Network ifname configuration migration
> 为了使 LuCI 正常工作，现有的网络配置需要更改。
> Upon pressing "Continue", ifname options will get renamed and the network will be restarted to apply the updated configuration.

查过了  上游代码原因 等上游大佬们修复吧  先下29号或者之前的版本

**Comment by gexqin** [comment]
感谢回复，坐等修复

**Comment by gexqin** [comment]
此问题已在X86-64-2021.06.11-1718 版本修复
